"""TikTok API for Business OAuth helper.

TikTok's current account-holder redirect rules require a public HTTPS URL with
no port, query string, or fragment, and a trailing slash.  Hermes cannot
receive that callback on a local-only listener, so this tool generates the
authorization URL and accepts the callback URL/code pasted by the user.

The client secret and resulting tokens are never accepted as model arguments.
Client credentials come from the environment and tokens are stored under the
profile-scoped Hermes home with owner-only permissions.
"""

from __future__ import annotations

import json
import os
import secrets
import stat
import tempfile
import time
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlencode, urlsplit

import httpx

from hermes_constants import get_hermes_home
from tools.registry import registry

_TIKTOK_AUTH_URL = "https://www.tiktok.com/v2/auth/authorize/"
_TIKTOK_TOKEN_URL = "https://business-api.tiktok.com/open_api/v1.3/tt_user/oauth2/token/"
_TOKEN_DIR_NAME = "tiktok"
_TOKEN_FILE_NAME = "tokens.json"
_STATE_FILE_NAME = "oauth-state.json"

_SCHEMA = {
    "name": "tiktok_oauth",
    "description": (
        "Authenticate a TikTok API for Business app. Use 'authorize' to get a "
        "TikTok account-holder authorization URL, then use 'exchange_code' with "
        "the full callback URL pasted from the browser (or its auth code). "
        "Also supports 'refresh', 'status', and 'logout'. Client credentials are "
        "read from TIKTOK_CLIENT_KEY and TIKTOK_CLIENT_SECRET; the redirect URI "
        "is read from tiktok.redirect_uri in config.yaml."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "action": {
                "type": "string",
                "enum": ["authorize", "exchange_code", "refresh", "status", "logout"],
                "description": "OAuth lifecycle operation.",
            },
            "scope": {
                "type": "string",
                "description": (
                    "Space-delimited TikTok scopes. If omitted, uses tiktok.scopes "
                    "from config.yaml."
                ),
            },
            "state": {
                "type": "string",
                "description": "Optional CSRF state. A cryptographically random state is generated by default.",
            },
            "callback_url": {
                "type": "string",
                "description": "The complete redirect URL copied from the browser after authorization.",
            },
            "code": {
                "type": "string",
                "description": "Authorization code, if callback_url is not supplied.",
            },
            "callback_state": {
                "type": "string",
                "description": "State returned alongside a manually supplied code.",
            },
            "disable_auto_auth": {
                "type": "boolean",
                "description": "Append TikTok's disable_auto_auth=1 flag to the authorization URL.",
            },
        },
        "required": ["action"],
    },
}


def _error(message: str, **extra: Any) -> str:
    return json.dumps({"status": "error", "message": message, **extra}, ensure_ascii=False)


def _ok(**data: Any) -> str:
    return json.dumps({"status": "ok", **data}, ensure_ascii=False)


def _client_key() -> str:
    return os.getenv("TIKTOK_CLIENT_KEY", "").strip()


def _client_secret() -> str:
    return os.getenv("TIKTOK_CLIENT_SECRET", "").strip()


def _config() -> dict[str, Any]:
    try:
        from hermes_cli.config import load_config_readonly

        value = load_config_readonly()
        return value if isinstance(value, dict) else {}
    except Exception:
        return {}


def _redirect_uri() -> str:
    cfg = _config()
    tiktok = cfg.get("tiktok", {})
    if not isinstance(tiktok, dict):
        return ""
    return str(tiktok.get("redirect_uri") or "").strip()


def _configured_scopes() -> list[str]:
    tiktok = _config().get("tiktok", {})
    scopes = tiktok.get("scopes", []) if isinstance(tiktok, dict) else []
    if isinstance(scopes, str):
        return [item for item in scopes.split() if item]
    if isinstance(scopes, list):
        return [str(item).strip() for item in scopes if str(item).strip()]
    return []


def validate_redirect_uri(value: str) -> tuple[bool, str]:
    """Validate TikTok account-holder redirect formatting rules."""
    value = str(value or "").strip()
    if not value:
        return False, "Set tiktok.redirect_uri in config.yaml to a public HTTPS callback URL."
    if len(value) < 10 or len(value) > 512:
        return False, "TikTok redirect URI length must be between 10 and 512 characters."
    if any(char.isspace() for char in value):
        return False, "TikTok redirect URI must not contain whitespace."

    try:
        parsed = urlsplit(value)
        port = parsed.port
    except ValueError:
        return False, "TikTok redirect URI has an invalid port or authority."

    if parsed.scheme != "https":
        return False, "TikTok redirect URI must start with https://."
    if not parsed.netloc or parsed.username or parsed.password:
        return False, "TikTok redirect URI must contain a valid public hostname."
    if port is not None:
        return False, "TikTok redirect URI cannot include a port."
    if parsed.query:
        return False, "TikTok redirect URI cannot include query parameters."
    if parsed.fragment:
        return False, "TikTok redirect URI cannot include a fragment."
    if not parsed.path.endswith("/"):
        return False, "TikTok redirect URI must end with /."
    return True, ""


def _token_dir() -> Path:
    return get_hermes_home() / _TOKEN_DIR_NAME


def _token_path() -> Path:
    return _token_dir() / _TOKEN_FILE_NAME


def _state_path() -> Path:
    return _token_dir() / _STATE_FILE_NAME


def _ensure_token_dir() -> Path:
    directory = _token_dir()
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    try:
        os.chmod(directory, stat.S_IRWXU)
    except OSError:
        pass
    return directory


def _read_json(path: Path) -> dict[str, Any] | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _write_json(path: Path, value: dict[str, Any]) -> None:
    directory = _ensure_token_dir()
    fd, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=directory, text=True)
    temporary = Path(temporary_name)
    try:
        os.fchmod(fd, stat.S_IRUSR | stat.S_IWUSR)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(value, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        try:
            os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
        except OSError:
            pass
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _delete_file(path: Path) -> bool:
    try:
        path.unlink()
        return True
    except FileNotFoundError:
        return False


def _require_credentials() -> tuple[str | None, str | None]:
    missing = []
    if not _client_key():
        missing.append("TIKTOK_CLIENT_KEY")
    if not _client_secret():
        missing.append("TIKTOK_CLIENT_SECRET")
    if missing:
        return None, "Set the TikTok client credentials in Hermes' secret environment: " + ", ".join(missing) + "."
    return _client_key(), None


def _extract_callback(callback_url: str) -> tuple[str, str | None, str | None]:
    parsed = urlsplit(callback_url.strip())
    query = parse_qs(parsed.query, keep_blank_values=True)
    error = query.get("error", [None])[0]
    error_description = query.get("error_description", [None])[0]
    code = query.get("code", [None])[0]
    state = query.get("state", [None])[0]
    if error:
        detail = error_description or error
        raise ValueError(f"TikTok authorization failed: {detail}")
    if not code:
        raise ValueError("Callback URL does not contain a code query parameter.")
    return code, state, error


def _response_json(response: httpx.Response) -> dict[str, Any]:
    try:
        payload = response.json()
    except (ValueError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"TikTok returned non-JSON HTTP {response.status_code}.") from exc
    if not isinstance(payload, dict):
        raise RuntimeError("TikTok returned an unexpected response shape.")
    if response.status_code >= 400:
        message = payload.get("message") or payload.get("error_description") or response.text[:300]
        raise RuntimeError(f"TikTok token request failed (HTTP {response.status_code}): {message}")
    if payload.get("code") not in (None, 0, "0"):
        message = payload.get("message") or payload.get("error") or "unknown TikTok error"
        raise RuntimeError(f"TikTok token request failed: {message}")
    return payload


def _token_data(payload: dict[str, Any]) -> dict[str, Any]:
    data = payload.get("data")
    if not isinstance(data, dict):
        data = payload
    if not data.get("access_token"):
        raise RuntimeError("TikTok response did not contain an access_token.")
    now = int(time.time())
    result = dict(data)
    try:
        if data.get("expires_in") is not None:
            result["expires_at"] = now + int(data["expires_in"])
        if data.get("refresh_expires_in") is not None:
            result["refresh_expires_at"] = now + int(data["refresh_expires_in"])
    except (TypeError, ValueError) as exc:
        raise RuntimeError("TikTok returned an invalid token lifetime.") from exc
    result["saved_at"] = now
    return result


def _post_token(form: dict[str, str]) -> dict[str, Any]:
    response = httpx.post(_TIKTOK_TOKEN_URL, data=form, timeout=30.0)
    return _token_data(_response_json(response))


def _authorize(args: dict[str, Any]) -> str:
    client_key, error = _require_credentials()
    if error:
        return _error(error)
    redirect_uri = _redirect_uri()
    valid, reason = validate_redirect_uri(redirect_uri)
    if not valid:
        return _error(reason, configuration="tiktok.redirect_uri")

    raw_scope = str(args.get("scope") or "").strip()
    scopes = raw_scope.split() if raw_scope else _configured_scopes()
    if not scopes:
        return _error(
            "Provide 'scope' or set tiktok.scopes in config.yaml. "
            "Use the scopes enabled for the TikTok Accounts permission in the app."
        )

    state = str(args.get("state") or "").strip() or secrets.token_urlsafe(32)
    _write_json(_state_path(), {"state": state, "created_at": int(time.time())})
    params = {
        "client_key": client_key,
        "response_type": "code",
        "scope": " ".join(scopes),
        "redirect_uri": redirect_uri,
        "state": state,
    }
    if args.get("disable_auto_auth"):
        params["disable_auto_auth"] = "1"
    return _ok(
        action="authorize",
        authorization_url=f"{_TIKTOK_AUTH_URL}?{urlencode(params)}",
        redirect_uri=redirect_uri,
        scope=scopes,
        state=state,
        next_step="Open authorization_url, approve access, then call exchange_code with the full callback URL.",
    )


def _exchange(args: dict[str, Any]) -> str:
    client_key, error = _require_credentials()
    if error:
        return _error(error)
    redirect_uri = _redirect_uri()
    valid, reason = validate_redirect_uri(redirect_uri)
    if not valid:
        return _error(reason, configuration="tiktok.redirect_uri")

    callback_url = str(args.get("callback_url") or "").strip()
    code = str(args.get("code") or "").strip()
    callback_state = str(args.get("callback_state") or "").strip() or None
    if callback_url:
        try:
            code, callback_state, _ = _extract_callback(callback_url)
        except ValueError as exc:
            return _error(str(exc))
    if not code:
        return _error("Provide either callback_url or code.")

    pending = _read_json(_state_path()) or {}
    expected_state = str(pending.get("state") or "")
    if expected_state and callback_state != expected_state:
        return _error("OAuth state mismatch; restart with action='authorize' and do not reuse the callback.")

    try:
        token = _post_token(
            {
                "client_id": client_key or "",
                "client_secret": _client_secret(),
                "grant_type": "authorization_code",
                "auth_code": code,
                "redirect_uri": redirect_uri,
            }
        )
    except (httpx.HTTPError, RuntimeError, ValueError) as exc:
        return _error(str(exc))

    _write_json(_token_path(), token)
    _delete_file(_state_path())
    return _ok(
        action="exchange_code",
        token_file=str(_token_path()),
        expires_at=token.get("expires_at"),
        refresh_expires_at=token.get("refresh_expires_at"),
        open_id=token.get("open_id"),
        advertiser_ids=token.get("advertiser_ids", []),
        scope=token.get("scope"),
    )


def _refresh() -> str:
    client_key, error = _require_credentials()
    if error:
        return _error(error)
    stored = _read_json(_token_path())
    refresh_token = str((stored or {}).get("refresh_token") or "").strip()
    if not refresh_token:
        return _error("No refresh token is stored. Run action='authorize' first.")
    try:
        token = _post_token(
            {
                "client_id": client_key or "",
                "client_secret": _client_secret(),
                "grant_type": "refresh_token",
                "refresh_token": refresh_token,
            }
        )
    except (httpx.HTTPError, RuntimeError, ValueError) as exc:
        return _error(str(exc))
    if not token.get("refresh_token"):
        token["refresh_token"] = refresh_token
    _write_json(_token_path(), token)
    return _ok(
        action="refresh",
        token_file=str(_token_path()),
        expires_at=token.get("expires_at"),
        refresh_expires_at=token.get("refresh_expires_at"),
        open_id=token.get("open_id"),
        advertiser_ids=token.get("advertiser_ids", []),
        scope=token.get("scope"),
    )


def _status() -> str:
    token = _read_json(_token_path())
    pending = _read_json(_state_path())
    now = int(time.time())
    if not token:
        return _ok(action="status", authenticated=False, authorization_pending=bool(pending))
    expires_at = token.get("expires_at")
    refresh_expires_at = token.get("refresh_expires_at")
    return _ok(
        action="status",
        authenticated=True,
        access_token_present=bool(token.get("access_token")),
        refresh_token_present=bool(token.get("refresh_token")),
        expired=bool(expires_at and int(expires_at) <= now),
        expires_at=expires_at,
        refresh_expires_at=refresh_expires_at,
        open_id=token.get("open_id"),
        advertiser_ids=token.get("advertiser_ids", []),
        scope=token.get("scope"),
        authorization_pending=bool(pending),
    )


def _handle(args: dict[str, Any], **_kwargs) -> str:
    action = str(args.get("action") or "").strip()
    if action == "authorize":
        return _authorize(args)
    if action == "exchange_code":
        return _exchange(args)
    if action == "refresh":
        return _refresh()
    if action == "status":
        return _status()
    if action == "logout":
        removed = _delete_file(_token_path())
        _delete_file(_state_path())
        return _ok(action="logout", removed=removed)
    return _error(f"Unknown action: {action!r}")


def check_tiktok_requirements() -> bool:
    return bool(_client_key() and _client_secret())


registry.register(
    name="tiktok_oauth",
    toolset="tiktok",
    schema=_SCHEMA,
    handler=_handle,
    check_fn=check_tiktok_requirements,
    requires_env=["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    description="TikTok API for Business OAuth authorization and token lifecycle",
    emoji="🎵",
)
